import { Button, Chip, Stack, Typography } from "@mui/material";
import { useQuery } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";

import { tasksApi } from "../../api/endpoints";
import type { CompletionResult, DailyActivity } from "../../api/types";
import { ApiErrorAlert } from "../../components/ApiErrorAlert";
import { Countdown } from "../../components/Countdown";
import { DataTable, type Column } from "../../components/DataTable";
import { DateTimeText, formatTimeIST } from "../../components/DateTimeText";
import { STATUS_LABEL } from "./labels";
import { SlaStateChip } from "./SlaBadge";

export const RESULT_LABEL: Record<CompletionResult, string> = {
  ON_TIME: "Completed on time", LATE: "Completed late", NO_DEADLINE: "Completed",
};

export function ResultChip({ result }: { result: CompletionResult | null }) {
  if (!result) return null;
  return <Chip size="small" color={result === "LATE" ? "error" : "success"} label={RESULT_LABEL[result]} />;
}

function timeIST(value: string | null) {
  return value ? formatTimeIST(value) : "—";
}

/** Phase 5.1: today's activities generated by the scheduler for me. Signing in only reads them;
 * start, deadline, SLA state and on-time / late all come from the backend. */
export function DailyActivities() {
  const navigate = useNavigate();
  const { data, error, isFetching, dataUpdatedAt } = useQuery({
    queryKey: ["daily-activities"], queryFn: () => tasksApi.dailyActivities(), refetchInterval: 60_000,
  });
  const columns: Column<DailyActivity>[] = [
    { key: "activity", header: "Activity", render: (a) => <Stack><strong>{a.responsibility?.name ?? a.title}</strong><Typography variant="caption" color="text.secondary">{a.reference}</Typography></Stack> },
    { key: "start", header: "Start", render: (a) => timeIST(a.scheduled_start) },
    { key: "deadline", header: "Deadline", render: (a) => a.deadline ? timeIST(a.deadline) : "No deadline" },
    { key: "status", header: "Status", render: (a) => STATUS_LABEL[a.status] },
    { key: "sla", header: "SLA", render: (a) => <SlaStateChip state={a.sla_state} /> },
    { key: "remaining", header: "Remaining", render: (a) => a.remaining_seconds === null ? "—" : <Countdown remainingSeconds={a.remaining_seconds} receivedAt={dataUpdatedAt} /> },
    { key: "completed", header: "Completed at", render: (a) => a.completed_at ? <Stack spacing={0.5}><DateTimeText value={a.completed_at} /><ResultChip result={a.completion_result} /></Stack> : "—" },
    { key: "open", header: "", render: (a) => <Button size="small" onClick={() => navigate(`/tasks/${a.task_id}`)}>Open</Button> },
  ];
  const rows = data?.activities ?? [];
  return (
    <>
      <ApiErrorAlert error={error} />
      <DataTable caption="Daily / scheduled responsibilities" columns={columns} rows={rows} getRowId={(a) => a.task_id}
        loading={isFetching} total={rows.length} page={0} onPageChange={() => undefined}
        emptyMessage="No daily activities have been generated for you today." />
    </>
  );
}
