from django.urls import path

from . import config_views as cfg
from . import review_views as rev
from .views import PerformanceCsvExportView, PerformanceExcelExportView, PerformanceReportView

urlpatterns = [
    path("performance/reports/", PerformanceReportView.as_view(), name="performance-report"),
    path(
        "performance/reports/export/csv/",
        PerformanceCsvExportView.as_view(),
        name="performance-report-csv",
    ),
    path(
        "performance/reports/export/excel/",
        PerformanceExcelExportView.as_view(),
        name="performance-report-excel",
    ),
    # --- Phase 7.1 KRA configuration ---
    path("performance/kpis/", cfg.KpiListView.as_view(), name="performance-kpis"),
    path("performance/kpis/<int:pk>/", cfg.KpiDetailView.as_view(), name="performance-kpi"),
    path("performance/plans/", cfg.PlanListView.as_view(), name="performance-plans"),
    path("performance/plans/<int:pk>/", cfg.PlanDetailView.as_view(), name="performance-plan"),
    path("performance/plans/<int:pk>/clone/", cfg.PlanCloneView.as_view(),
         name="performance-plan-clone"),
    path("performance/plans/<int:pk>/activate/", cfg.PlanActivateView.as_view(),
         name="performance-plan-activate"),
    path("performance/plans/<int:pk>/retire/", cfg.PlanRetireView.as_view(),
         name="performance-plan-retire"),
    path("performance/plans/<int:pk>/lines/", cfg.PlanLineListView.as_view(),
         name="performance-plan-lines"),
    path("performance/plans/<int:pk>/deduction-rules/", cfg.DeductionRuleListView.as_view(),
         name="performance-plan-deduction-rules"),
    path("performance/plan-lines/<int:pk>/", cfg.PlanLineDetailView.as_view(),
         name="performance-plan-line"),
    path("performance/plan-lines/<int:pk>/components/", cfg.ComponentListView.as_view(),
         name="performance-plan-line-components"),
    path("performance/components/<int:pk>/", cfg.ComponentDetailView.as_view(),
         name="performance-component"),
    path("performance/deduction-rules/<int:pk>/", cfg.DeductionRuleDetailView.as_view(),
         name="performance-deduction-rule"),
    path("performance/scoring-rules/", cfg.ScoringRuleListView.as_view(),
         name="performance-scoring-rules"),
    path("performance/scoring-rules/<int:pk>/", cfg.ScoringRuleDetailView.as_view(),
         name="performance-scoring-rule"),
    path("performance/scoring-rules/<int:pk>/clone/", cfg.ScoringRuleCloneView.as_view(),
         name="performance-scoring-rule-clone"),
    path("performance/scoring-rules/<int:pk>/activate/", cfg.ScoringRuleActivateView.as_view(),
         name="performance-scoring-rule-activate"),
    path("performance/scoring-rules/<int:pk>/retire/", cfg.ScoringRuleRetireView.as_view(),
         name="performance-scoring-rule-retire"),
    path("performance/band-schemes/", cfg.BandSchemeListView.as_view(),
         name="performance-band-schemes"),
    path("performance/band-schemes/<int:pk>/", cfg.BandSchemeDetailView.as_view(),
         name="performance-band-scheme"),
    path("performance/band-schemes/<int:pk>/clone/", cfg.BandSchemeCloneView.as_view(),
         name="performance-band-scheme-clone"),
    path("performance/band-schemes/<int:pk>/activate/", cfg.BandSchemeActivateView.as_view(),
         name="performance-band-scheme-activate"),
    path("performance/band-schemes/<int:pk>/retire/", cfg.BandSchemeRetireView.as_view(),
         name="performance-band-scheme-retire"),
    path("performance/plan-defaults/", cfg.PlanDefaultListView.as_view(),
         name="performance-plan-defaults"),
    path("performance/plan-defaults/<int:pk>/end/", cfg.PlanDefaultEndView.as_view(),
         name="performance-plan-default-end"),
    path("performance/assignments/", cfg.OverrideListView.as_view(),
         name="performance-assignments"),
    path("performance/assignments/<int:pk>/end/", cfg.OverrideEndView.as_view(),
         name="performance-assignment-end"),
    path("performance/plan-resolution/", cfg.PlanResolutionView.as_view(),
         name="performance-plan-resolution"),
    # --- Phase 7.3 KRA monthly review ---
    path("performance/months/calculate/", rev.KraMonthCalculateView.as_view(),
         name="performance-month-calculate"),
    path("performance/months/<int:pk>/", rev.KraMonthDetailView.as_view(),
         name="performance-month"),
    path("performance/months/<int:pk>/blockers/", rev.KraMonthBlockersView.as_view(),
         name="performance-month-blockers"),
    path("performance/months/<int:pk>/submit/", rev.KraMonthSubmitView.as_view(),
         name="performance-month-submit"),
    path("performance/months/<int:pk>/return/", rev.KraMonthReturnView.as_view(),
         name="performance-month-return"),
    path("performance/months/<int:pk>/finalize/", rev.KraMonthFinalizeView.as_view(),
         name="performance-month-finalize"),
    path("performance/months/<int:pk>/reopen/", rev.KraMonthReopenView.as_view(),
         name="performance-month-reopen"),
    path("performance/months/<int:pk>/kpis/<int:kpi_id>/adjust/", rev.KraKpiAdjustView.as_view(),
         name="performance-month-kpi-adjust"),
    path("performance/months/<int:pk>/deductions/", rev.KraDeductionListView.as_view(),
         name="performance-month-deductions"),
    path("performance/months/<int:pk>/deductions/<int:application_id>/reverse/",
         rev.KraDeductionReverseView.as_view(), name="performance-month-deduction-reverse"),
    path("performance/months/<int:pk>/gap-decisions/", rev.KraGapDecisionView.as_view(),
         name="performance-month-gap-decisions"),
    path("performance/months/<int:pk>/components/<int:component_id>/manual-entry/",
         rev.KraManualEntryView.as_view(), name="performance-month-manual-entry"),
    path("performance/months/<int:pk>/components/<int:component_id>/mark-na/",
         rev.KraManualNaView.as_view(), name="performance-month-mark-na"),
    path("performance/approved-leave/", rev.KraLeaveListView.as_view(),
         name="performance-approved-leave"),
    path("performance/approved-leave/<int:pk>/cancel/", rev.KraLeaveCancelView.as_view(),
         name="performance-approved-leave-cancel"),
    path("performance/task-overrides/", rev.KraTaskOverrideListView.as_view(),
         name="performance-task-overrides"),
    path("performance/task-overrides/<int:pk>/remove/", rev.KraTaskOverrideRemoveView.as_view(),
         name="performance-task-override-remove"),
    path("performance/annual/", rev.KraAnnualView.as_view(), name="performance-annual"),
]
